### ISSUE TITLE
現在のmasterにてauto itrが一部未定義となっている

### ISSUE THREAD

**Issue by MR782** [Tatsuki5274/stern#111]
//トランザクションの実行
	for (auto itr = enemy_transaction->begin(); itr != enemy_transaction->end(); ++itr) {
		enemys->push_back(std::move((*itr)));	//トランザクションから実体へ所有権を移動する
	}
この文で itr : 定義されていない識別子です　　とでる
(赤線はでていない)

**Comment by Tatsuki5274** [comment]
`enemys->push_back(std::move((*itr)));`
をコメントアウトするとエラー消える？
それとも消えない？
