### ISSUE TITLE
プレイヤーの無敵時間が継続している

### ISSUE THREAD

**Issue by MR782** [Tatsuki5274/stern#165]
ゲームシーン内でプレイヤーがダメージを受けた直後にポーズやクリアに遷移してもう一度ゲーム画面に入るとしばらくの間プレイヤーが無敵となっている

ブランチ:現在のmaster

**Comment by iipyon** [comment]
というかプレイヤーのプロパティ全て初期化されて無いね
HPとかも減ったまま
