### ISSUE TITLE
Playerのコンストラクタでct(CoreTask)のメンバオブジェクトにアクセスすると例外が起こる

### ISSUE THREAD

**Issue by Tatsuki5274** [Tatsuki5274/stern#51]
**症状**
ctにアクセスすると例外(return pointer to class object)を投げてしまう。
同じファイル内のupdate()では正常に動作する。

**試したこと**
coretask.hがincludeされているか確認。
playerのコンストラクタの前に必要なインスタンス(今回はkeyboard)が生成されているか確認。

**問題のブランチ**
UpdateForGraphicResource2

**コード**
```
Player::Player()
{
・・省略・・
	interval = 0;
	foot_status = false;
	ct->keyboard->update(); //例外が発生する処理
・・省略・・
}
```

もし解決策がわかれば教えてください！

**Comment by iipyon** [comment]
masterの段階で例外が発生することを確認
めっちゃ前の段階からヤってるな
