### ISSUE TITLE
Destroy問題

### ISSUE THREAD

**Issue by MR782** [Tatsuki5274/stern#77]
リストをdestroy()で消すことができなかった
list->lead();
while(list->exist())
{
list->destroy();
}
を行うとフリーズが発生
１度クリア画面に遷移して再度ゲームタスクに入るとき

**Comment by Tatsuki5274** [comment]
具体的に何のブランチで発生していて、どのファイルのどのクラスのどのメソッドでの処理？
或いは全てのdestroyがだめ？

**Comment by MR782** [comment]
masterから派生したブランチで発生
SpawnEnemyで記述した（上記の処理）をStageSelectTask（ClearTaskでも）で呼び出すとフリーズが発生
Destroy()のみだとフリーズはせず（削除もされない）Lead()を呼んでループを回すとフリーズが発生
現在のMasterには入っていない可能性があるためなかった場合適当に作ってやってみてください
